version: "3.3"

services:
  bot:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
